[env]
TERM = "xterm-256color"

[font]
normal = { family = "Hack Nerd Font Mono", style = "Regular" }
bold = { family = "Hack Nerd Font Mono", style = "Bold" }
italic = { family = "Hack Nerd Font Mono", style = "Italic" }
size = 12

[window]
padding.x = 14
padding.y = 14

[keyboard]
bindings = [
  { mods = "Command", key = "N", action = "CreateNewWindow" }
]

[[hints.enabled]]
regex = "[a-zA-Z0-9/\\-_\\.]+(:\\d+)(:\\d*)?"
command = { program = "code", args = [ "--goto" ] }
mouse = { enabled = true, mods = "Command" }
